models/Post.php
<?php

namespace app\models;

use Yii;
use app\models\User;
/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $pid
 * @property string $title
 * @property string @article
 * @property string $uid
 * @property string $timestamp
 *
 * @property Users $u
 */
class Post extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['pid', 'title','article', 'uid'], 'required'],
            [['timestamp'], 'safe'],
            [['pid', 'title', 'uid'], 'string', 'max' => 128],
            [['article'], 'string', 'max' => 256],
            [['uid'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['uid' => 'uid']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pid' => 'Pid',
            'title' => 'Title',
            'article' => 'Article',
            'uid' => 'Uid',
            'timestamp' => 'Timestamp',
        ];
    }

    /**
     * Gets query for [[U]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getU()
    {
        return $this->hasOne(User::className(), ['uid' => 'uid']);
    }
}

models/User.php
<?php

namespace app\models;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $uid
 * @property string $account
 * @property string $pwd
 * @property string $name
 * @property string $authKey
 * @property string $accessToken
 */
class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    public static function tableName()
    {
        return 'users';
    }
    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token'=>$token]);
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['account'=>$username]);
    }

    public function getUId()
    {
        return $this->uid;
    }
    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
    
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['uid','account', 'pwd', 'name','authKey','accessToken'], 'required'],
            [['account', 'name'], 'string', 'max' => 12],
            [['uid','pwd','authKey','accessToken'], 'string', 'max' => 128],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'uid' => 'Uid',
            'account' => 'Account',
            'pwd' => 'Pwd',
            'name' => 'Name',
            'authKey' => 'authKey',
            'accessToken' => 'accessToken',
        ];
    }
}

models/Userform.php
<?php
namespace app\models;
use yii\base\Model;
use app\models\User;
class Userform extends Model{
    public $account;
    public $pwd;
    public $name;
    public $pwd_confirm;
    public function rules(){
        return [
            [['account','pwd','name','pwd_confirm'],'required'],
            [['account','pwd','name'],'string','max'=>12],
            ['account',function(){
                if(User::findOne(['account'=>$this->account])) $this->addError('account','The account has been registed.');
            }],
            ['pwd_confirm','compare','compareAttribute'=>'pwd','message'=>'Password do not match']
        ];
    }
    /**
     * regist
     *
     * @return User[null on failed]
     */
    public function regist(){
        $user = new User;
        $user->account = $this->account;
        $user->pwd = \Yii::$app->getSecurity()->generatePasswordHash($this->pwd);
        $user->name = $this->name;
        $user->uid = \Yii::$app->security->generateRandomString(12);
        $user->authKey = \Yii::$app->security->generateRandomString(12);
        $user->accessToken = \Yii::$app->security->generateRandomString(12);
        return $user->save() ? $user : null;
    }
    public function login(){
        $user = User::findOne(['account'=>$this->account]);
        if($user == null) return null;
        return \Yii::$app->getSecurity()->validatePassword($this->pwd,$user->pwd)?$user:null;
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\rest\ActiveController;
use app\models\Post;
class PostController extends ActiveController
{
    public $enableCsrfValidation = false;
    public $modelClass = 'app\models\Post';
    
    public function actions()  
    {  
        $actions = parent::actions();  
        unset($actions['view']);
        return $actions;
    }  

    public function actionView($id){
        return $this->findModel($id);
    }
    public function findModel($id){
        $modelClass = $this->modelClass;
        if (($model = $modelClass::findAll(['pid'=>$id])) !== null) {  
            return $model;  
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;

class SiteController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['add', 'update'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['add', 'update'],
                        'roles' => ["@"]
                    ]
                ],
            ]
        ];
    }
    public function actionIndex()
    {
        return $this->render('index');
    }
    public function actionError()
    {
        return $this->render('error');
    }
    public function actionAdd()
    {
        return $this->render('add');
    }
    public function actionUpdate()
    {
        return $this->render('update');
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Userform;
use yii\filters\AccessControl;

class UsersController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['login', 'logout', 'signup'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login','signup'],
                        'roles' => ['?'] //not yet authenticated
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'] //has been authenticated
                    ],
                ],
            ]
        ];
    }
    public function actionLogin()
    {
        $model = new Userform();
        if ($model->load(Yii::$app->request->post())) {
            if($user = $model->login()){
                Yii::$app->user->login($user);
                return $this->goHome();
            }
            else{
                return $this->render('login', ['status' => 403,'model'=>$model,'message'=>'account or password is wrong.']);
            }
        }
        return $this->render('login', ['model'=>$model]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionSignup()
    {
        $model = new Userform();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($user = $model->regist()) {
                Yii::$app->user->login($user);
                return $this->goHome();
            }
        }
        return $this->render('regist', ['model' => $model]);
    }
}

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">

<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body class="d-flex flex-column h-100">
    <?php $this->beginBody() ?>

    <header>
        <?php
        NavBar::begin([
            'brandLabel' => Yii::$app->name,
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
            ],
        ]);
        $arr = [
                'options' => ['class' => 'navbar-nav'],
                'items' => [
                    ['label' => 'Home', 'url' => ['/site/index']],
                ],
            ];
        if (Yii::$app->user->isGuest) {
            array_push(
                $arr['items'],
                ['label' => 'Login', 'url' => ['/users/login']],
                ['label' => 'Sign up', 'url' => ['/users/signup']],
            );
        } else {
            array_push(
                $arr['items'],
                ['label'=> "Logout(".Yii::$app->user->identity->name.")",'url'=>['users/logout']],
            );
        }
        echo Nav::widget($arr);
        NavBar::end();
        ?>
    </header>

    <main role="main" class="flex-shrink-0">
        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </main>

    <footer class="footer mt-auto py-3 text-muted">
        <div class="container">
            <p class="float-left">&copy; Mi Meow<?= date('Y') ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>

views/site/add.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-3">標題</div>
        </div>
        <div class="row">
            <input id="title" class="col-8">
        </div>
        <div class="row">
            <div class="col-3">文章</div>
        </div>
        <div class="row">
            <textarea class="col-12" id="article"></textarea>
        </div>
        <div class="row">
            <div class="col-10"></div>
            <div class="col-2">
                <?= Html::button('送出', ['class'=>'btn btn-success','onclick' => "
                    $.ajax({
                        type:'POST',
                        url:'" . Url::toRoute(['post']) . "',
                        success: function(rs){
                            location.href='".Url::toRoute(['site/index'])."'
                        },
                    })
                "]) ?>
            </div>
        </div>
    </div>
</body>

</html>

views/site/error.php
Error~

views/site/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-4"><h3>Yii_Pratice</h3></div>
            <div class="col-2"><?=Html::a("新增",Url::toRoute(['site/add']))?></div>
        </div>
        <div class="row">
            <div class="col-2">#id</div>
            <div class="col-6">Title</div>
            <div class="col-2">User</div>
            <div class="col-2">Time</div>
        </div>
    </div>
</body>

</html>

views/users/login.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin()?>
<h3><?php if(isset($message)) echo $message;?></h3>
<?=$form->field($model,'account')->label("帳號")?>
<?=$form->field($model,'pwd')->passwordInput()->label("密碼")?>
<?=Html::submitButton('Login',['class'=>'btn btn-success'])?>
<?php ActiveForm::end() ?>

views/users/regist.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<?php $form = ActiveForm::begin()?>
<?=$form->field($model,'account')->label("帳號")?>
<?=$form->field($model,'pwd')->passwordInput()->label("密碼")?>
<?=$form->field($model,'pwd_confirm')->passwordInput()->label("二次密碼")?>
<?=$form->field($model,'name')->label("暱稱")?>
<?=Html::submitButton('register!',['class'=>'btn btn-success'])?>
<?php ActiveForm::end() ?>